### ISSUE TITLE
TypeScript compiler errors when importing the module

### ISSUE THREAD

**Issue by keeprocking** [vitalishapovalov/jest-decorated#129]
Hi,

When trying to import the module like this:
```
import { BeforeAll, AfterAll } from "@jest-decorated/core";
```
I'm getting the following error:
```
Could not find a declaration file for module '@jest-decorated/core'. '/workspace/node_modules/@jest-decorated/core/dist/index.umd.js' implicitly has an 'any' type.
```

Importing into global scope, i.e.
```
import "@jest-decorated/core/globals";
```
works fine, but I'd like to keep the global scope as clean as possible.

@jest-decorated/core version: 0.0.19
TypeScript version: 4.1.3
tsconfig:
```
{
    "compilerOptions": {
        "strict": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "target": "ES6",
        "moduleResolution": "node"
    },
    "include": [
        "src/**/*"
    ]
}
```

Could you please advise? Thanks.

**Comment by vitalishapovalov** [comment]
Hello!
Thank you for reporting the issue!

Indeed, core module's package.json is missing the `types` field (like this one for react module https://github.com/vitalishapovalov/jest-decorated/blob/master/packages/react/package.json#L29)

Fixed here https://github.com/vitalishapovalov/jest-decorated/pull/130

Will make a release this weekend.

**Comment by vitalishapovalov** [comment]
Please, try to use [this release](https://github.com/vitalishapovalov/jest-decorated/releases/tag/v0.0.20)

Create a new issue in case of any.

Thanks! Have a good day!

**Comment by keeprocking** [comment]
Works perfectly, thanks a lot for the quick fix.
